### ISSUE TITLE
Code Arm subsystem and commands

### ISSUE THREAD

**Issue by neuenfeldttj** [The-Charge/RapidReact2022#20]
Firstly, create an Arm subsystem. As of right now, for the intake we're using one TalonSRX and for the lift mechanism we're using pistons (2 solenoids). 

Also, create an IntakeCargo command where you set the motor to a certain speed (as a parameter) and a DeliverCargo command that is the exact same but inverts the motor output.

Create a LiftArm Instant command that activates the solenoid (true). 
Create a LowerArm InstantComand that lowers the arm (set to false).

**Comment by Granto1** [comment]
Coded, need extensive testing.
